### ISSUE TITLE
Can't query embedded document property

### ISSUE THREAD

**Issue by endikamontejo** [cloudant/CDTDatastore#151]
I have a document looking like the following: http://pastie.org/private/kmdctsbhgcxx8g9m2msipg
I want to query the documents given a concrete type and uriList.source.

To be able to query this, I create the indexes for those properties as following:

``` objc
[self.dataStore ensureIndexed:@[@"type"] withName:@"docType"];
[self.dataStore ensureIndexed:@[@"uriList.source", @"uriList.url"] 
                     withName:@"documentUriList"];
```

So, I create the query:

``` objc
CDTQResultSet *result = [[self.couchDBProvider getDataStore] 
    find:@{@"type": type, @"uriList.source": source} 
    skip:0 
   limit:0 
  fields:nil 
    sort:nil];
```

But get no result at all.

Seems that the problem is that uriList is an array of jsons and this is not managed

**Comment by alfinkel** [comment]
I believe that this is currently an unsupported feature.  There is reference to this in the _Unsupported features_ section of the query documentation.  Under the _Arrays_ heading we have a bullet item for `Dotted notation to index or query sub-documents in arrays.` https://github.com/cloudant/CDTDatastore/blob/master/doc/query.md#unsupported-features

I added an internal case referencing this issue so that we can use it to prioritize this enhancement.

**Comment by mikerhodes** [comment]
Agreed, currently unsupported. But yes, I can see it's pretty useful as it's essentially impossible to index the sub-objects as-is.

**Comment by ricellis** [comment]
Closing as this library is now EOL and this issue won't be fixed here.
The issue has been [tagged `EOL`](https://github.com/cloudant/CDTDatastore/issues?q=is%3Aissue+label%3AEOL) in case any forks want to import it.
