### ISSUE TITLE
any support for replication of named documentation?

### ISSUE THREAD

**Issue by niexiaoguang** [cloudant/CDTDatastore#185]
according the documentation of cloudant about the named documentation replication : 

```
Example replication of specific documents:
```

{
  "source": "http://username:password@example.org/example-database",
  "target": "http://username:password@127.0.0.1:5984/example-database",
  "doc_ids": ["foo", "bar", "baz"]
}

the CDTDatastore has any function for that?

like  
        var pullReplication = CDTPullReplication(source: datastore, target: remoteDatabaseURL, ["doc1","doc2"] )

thanks

**Comment by mikerhodes** [comment]
You can't use named document replication yet as a pull replication option. We should add it though :)

Instead, the solution right now is to use a filtered replication instead, and pass in the list of document IDs as an argument to the filter. Unfortunately this is slower (the filter function is JS rather than within the database Erlang code), but it's the best approach right now.

**Comment by niexiaoguang** [comment]
Thanks for reply, waiting for the new function  
------------------ Original ------------------

**Comment by navaneet** [comment]
Is this feature in development? We actually require this feature since the standard filter based approach is too slow for our purpose as we have a very large set of documents.

**Comment by ricellis** [comment]
No, it is not in development and is not planned for now, but thanks for feeding back as it helps us prioritize.

**Comment by ricellis** [comment]
Closing as this library is now EOL and this issue won't be fixed here.
The issue has been [tagged `EOL`](https://github.com/cloudant/CDTDatastore/issues?q=is%3Aissue+label%3AEOL) in case any forks want to import it.
