### ISSUE TITLE
Mismatch between documentation and version 1.0.0

### ISSUE THREAD

**Issue by simonmcl** [cloudant/CDTDatastore#222]
The replication documentation references a method `startWithTaskGroup`. This method does not exist inside 1.0.0. I had to point cocoapods directly at master to use the feature. 

I'm guessing someone forgot to release a new pod version when the feature was merged in?

**Comment by rhyshort** [comment]
The documentation at the head of master matches the code that is present there, this is currently code which will become part of the 1.1 release. To see the documentation for the latest released version you should either use [cocoadocs](http://cocoadocs.org/docsets/CDTDatastore/1.0.0/) or browse the source tree at the tag for [1.0.0](https://github.com/cloudant/CDTDatastore/tree/b7d6f0ba6a6db0ff1c216a85ec53c06b36038d9d). 

I hope this clears things up.

**Comment by simonmcl** [comment]
Should it not have been pushed to a develop branch in that case? When someone opens github they are, by default, brought to the master branch. So everyone will start reading documentation that is not accurate compared to the currently released version.

That is very confusing.

**Comment by rhyshort** [comment]
We don't have a develop branch and we don't follow git flow which is the model I think you are referring to with a develop and master branches. Many other projects do the same. It is something that can be confusing, but at least for me once I got used to the idea that the master is where development takes place it became second nature to go to the releases screen to pick the tag I needed.

**Comment by simonmcl** [comment]
Yes the idea came from GitFlow but most use it anyway for various reasons. Case and point, I googled how to do background replication using the Cloudant SDK and was brought straight into your docs, which were in the master branch, whose readme says `pod v1.0.0`.

I've yet to come across a cocoapod where, unless by mistake, the master wasn't pointing to the latest release. I would imagine the same is true for the majority of developers, especially those that know very little about how cocoapods works.

You are going to cause yourself a lot of issues with this going forward as IBM continues to advertise Cloudant and developers come looking for the SDK. For your own sake, you should try clean it up after you next release.

**Comment by mikerhodes** [comment]
I think we'll have to disagree on the point around most cocoapod repos having master pointing at the latest tagged release and use of gitflow-like semantics. Looking at the first three pods that came to my mind (Alamofire, Specta, PonyDebugger) none follow either pattern.

I agree, though, with the underlying point you make: I've rarely come across code snippets within a README.md that didn't work for the latest release (and ours does, mostly, but we've been making a bunch of changes for 1.0.0 releases recently).

That's not saying there isn't an issue here, of course: it's been obvious for a long time that there's an issue with the main docs being in the repo, which isn't tied to a particular release. This is still the case because few of the approaches we've come up with so far have been particularly satisfying, rather than it not being recognised.

A first step would be to point users towards the documentation for the release, i.e., http://cocoadocs.org/docsets/CDTDatastore/1.0.0/. Clearly this doesn't help with stuff in the `/doc/` folder, but at least it's a step forward.

We're experimenting with ways to fix this while maintaining up-to-date docs in some of our other repos, e.g., github.com/cloudant/java-cloudant, and hopefully will be able to make this situation less confusing in future.
