### ISSUE TITLE
Confusing Swift Interface

### ISSUE THREAD

**Issue by rhyshort** [cloudant/CDTDatastore#258]
The generated Swift interface for CDTDatatore is confusing and for some features unusable. For example the `CDTDocumentRevision` class has 4 init methods each with different arguments and nullability. The macros used to manipulate the logging levels are not imported into swift thus Applications written in swift cannot control the logging levels for our classes.

It needs to be investigated how this can be improved, either using new Objc Language features announced at WWDC, or by creating a Swift front end which simplifies the interface. The problem with changing the mapping will result in the breaking changes for the swift interface so this may be in conflict with semver and have to be pushed to a major release rather than a minor.

**Comment by navaneet** [comment]
Is it possible for you guys to provide a working swift 4 sample with background foreground scenarios considered along with long duration replication with say large sets of documents so that we can have an idea of the proper usage of the library for error handling while downloading large sets of documents. We understand that iOS might not allow to continue downloading in the background for extended periods of time however the proper error handling needs to be demonstrated so that the same can be interleaved with out app logic. Ours generally run into 10,000+ documents and lack of any swift 4 related materials is making it harder for us to properly handle the different scenarios.

E.g. we recently ran into an issue wherein replicatorDidComplete is called with CDTReplicatorState.complete even with partial replication when network is switched on and off very frequently and we have no idea how to fix it as we completely rely upon CDTDatastore to tell us about the replication complete event.

**Comment by ricellis** [comment]
Closing as this library is now EOL and this issue won't be fixed here.
The issue has been [tagged `EOL`](https://github.com/cloudant/CDTDatastore/issues?q=is%3Aissue+label%3AEOL) in case any forks want to import it.
