### ISSUE TITLE
Pull replication in example project takes forever when I use my own database

### ISSUE THREAD

**Issue by romanzes** [cloudant/CDTDatastore#282]
Hello,
I have no experience with CDTDatastore or Cloudant in general and learning it by documentation and examples. Currently I am trying to figure out how to perform replications. So I opened the [sample project](https://github.com/cloudant/CDTDatastore/tree/master/Project) and both push and pull replications in it worked as I expected. Then I tried to aim the project to my own database and found that push replications work pretty well, but pull replications now take forever to complete.
STR:
1. Clone CDTDatastore project.
2. `pod install`, open workspace in Xcode.
3. Run project, click sync button, make sure that new items are appeared.
4. Create new database named 'todo' in Cloudant dashboard.
5. Go to Permissions, generate API key.
6. Give _admin permissions to the generated API key.
7. Change username, password, db_name and urls in CDTTodoReplicator.
8. Run project, add several items, sync.
9. Make sure that new items are appeared in Cloudant dashboard.
10. Delete application, run project again.
11. Try to sync.
Result: there are no previously added items, pull replication callback never fired (unlike push callback).

Am I missing something? Maybe there should be additional setup in dashboard?

**Comment by romanzes** [comment]
It seems the issue has appeared recently, in [this commit](https://github.com/cloudant/CDTDatastore/commit/d08d76f5db92a356d4ba0fd894678e1155cd6a0f). After checkout to previous commit pull replications are working fine.

**Comment by rhyshort** [comment]
Yeah, we've been trying to track down the exact problem with the code in the commit you mention. This bug is limited to CouchDB 2.0 and some Cloudant clusters running the next generation of our database core database software, known to us as DBNext.

There is a work around for now, if you can either create a new cloudant account on a cluster not running this software, or you can contact support via the dashboard and get them to move your account to one of the clusters not running the new version.

A list of clusters currently running DBNext

- Porter 
- Sling

**Comment by rhyshort** [comment]
@romanzes Support have moved your account to `Mead` replications should start to work again with 1.1.0.

**Comment by tomblench** [comment]
@romanzes just as an update we have a fix for this and should be able to release the fixed version of the library on Monday.

**Comment by tomblench** [comment]
@romanzes sorry for the delay - we have fixed the _bulk_get issue in our latest release which is 1.1.1
