### ISSUE TITLE
Try to speed up travis CI

### ISSUE THREAD

**Issue by ricellis** [cloudant/CDTDatastore#286]
Some tests take too long to execute on travis, we need to fix this or at the least switch them off so that the builds can complete quickly.
Docker containers may or may not help:
Try adding `sudo: false` to the `.travis.yml` file and seeing if we can get faster travis builds using the container infrastructure.

**Comment by tomblench** [comment]
Here are some timings from running on my own machine (clean checkout):

```
time (pod install; cd project && pod install; cd ..; rake travis)
...
real	11m58.936s
user	9m20.820s
sys	5m41.391s
```

From summing the `(x.y seconds)` from each unit test, the total time spent in tests is `262.261s` or approx `4m22s`. This means that `36.4%` of the time is spent in unit tests - the rest is compiling, etc.

**Comment by tomblench** [comment]
Note `sudo: false` is not applicable for OSX https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments

**Comment by rhyshort** [comment]
Interesting, if its only spending ~4m in tests, why are we looking at build times of around 30minutes? maybe caching the pods directory might help things along? https://docs.travis-ci.com/user/caching/#CocoaPods

**Comment by tomblench** [comment]
@rhyshort the proportions on travis are probably similar - so if a travis build takes 30 minutes total I would expect 10 minutes is the actual tests. The conclusion seems to be that travis is just slower because their Mac infrastructure is over-subscribed and under-provisioned.

Caching could help but it seems odd to start using tricks like that on a build system which is supposed to eliminate sources of random error by building everything in a clean environment.

My conclusion is that we should be doing a smaller set of tests on Travis to catch those "I broke the build" moments, and move the more intensive testing on to our in-house infrastructure.

**Comment by tomblench** [comment]
Done in #229
