### ISSUE TITLE
Update sample project

### ISSUE THREAD

**Issue by tomblench** [cloudant/CDTDatastore#406]
See https://github.com/cloudant/CDTDatastore/pull/405#issuecomment-346039612 - the sample should show users how to stop replications when the app is backgrounded.

It's also worth considering reverting to the previous "replication-policy" style sample code which existed before [this change](https://github.com/cloudant/CDTDatastore/commit/3a4429130ce08df72f7a1a94d30e0a6fd30ae7ae). There's a tension between a simple example and something which shows all the bells and whistles (as was discussed on #266), but the original sample would be useful to show to app developers who want code which automatically syncs on a schedule and adjusts its behaviour depending on whether it's in the foreground or background etc.

**Comment by navaneet** [comment]
Please provide a swift 4 working sample as well, it's very difficult to find any swift example for CDTDatastore.

**Comment by tomblench** [comment]
@navaneet sorry but a swift example isn't a priority right now

**Comment by navaneet** [comment]
Ok I understand, please give us an Objective C working sample so that we can test against it and bridge the code as required.

**Comment by tomblench** [comment]
@navaneet there's a sample project at https://github.com/cloudant/CDTDatastore/tree/master/Project plus extensive documentation in the https://github.com/cloudant/CDTDatastore/tree/master/doc, the README.MD file and appledocs comments. Plus the project is open source so you can read the source or follow it in a debugger.

Unfortunately we have other bugfixes and feature requests across this library and the other sync/client libraries that we provide and we have to prioritise resources. I'll look into the other bugs you raised.

**Comment by navaneet** [comment]
@tomblench We have extensively gone through all the extensive documentation, problem is that the sample is not detailed enough and doesn't cover the required error handling scenarios. 

E.g. The sample shows the following

```
[self.datastore pullReplicationWithSource:[self replicatorURL]
                            completionHandler:^(NSError *_Nullable error) {
                              __strong CDTViewController *strongSelf = weakSelf;
                              [strongSelf.datastore
                                  pushReplicationWithTarget:[strongSelf replicatorURL]
                                          completionHandler:^(NSError *_Nullable error) {
                                            __strong CDTViewController *strongSelf = weakSelf;
                                            [strongSelf toggleCompletedShown:nil];
                                          }];
                            }];
```

Whereas in the documentation 

https://github.com/cloudant/CDTDatastore/blob/master/doc/replication.md 

it mentions only the usage of delegates instead of callbacks.

```
/**
* Called when the replicator changes state.
*/
-(void) replicatorDidChangeState:(CDTReplicator*)replicator;

/**
* Called whenever the replicator changes progress
*/
-(void) replicatorDidChangeProgress:(CDTReplicator*)replicator;

/**
* Called when a state transition to COMPLETE or STOPPED is
* completed.
*/
- (void)replicatorDidComplete:(CDTReplicator*)replicator;

/**
* Called when a state transition to ERROR is completed.
*/
- (void)replicatorDidError:(CDTReplicator*)replicator info:(NSError*)info;
```
 So which one should we use, and which one is recommended? The documentation is not in sync with the sample so we are a bit confused as to what the best practices for using CDTDatastore are.

Also the sample doesn't cover the scenario wherein we might start a replication and then the app moves to the background which is a very normal use case and is only briefly mentioned in the documentation. The error handling conditions are not mentioned in detail.

E.g.     

`func replicatorDidComplete(_ replicator: CDTReplicator) {
  if replicator.state == CDTReplicatorState.complete {
` 
The above function actually seems to pass a state that can be accessed from CDTReplicator as mentioned below:

```
typedef NS_ENUM(NSInteger, CDTReplicatorState) {
    /**
     * The replicator is initialised and is ready to start.
     */
    CDTReplicatorStatePending,
    /**
     * A replication is in progress.
     */
    CDTReplicatorStateStarted,
    /**
     * The last replication was stopped using -stop
     */
    CDTReplicatorStateStopped,
    /**
     * -stop has been called and the replicator is being removed from the replication thread.
     */
    CDTReplicatorStateStopping,
    /**
     * The last replication successfully completed.
     */
    CDTReplicatorStateComplete,
    /**
     * The last replication completed in error.
     */
    CDTReplicatorStateError
};
```
This information we couldn't find within the documentation and had to actually check though the library code and debug to figure it out, now the next question that arises is how do we make sure the following states are reliable since we are encountering issues with the same and we are unable to find neither documentation nor a sample that demonstrates the same.

While we understand your situation we really need some help with these scenarios.

**Comment by tomblench** [comment]
Also note that a minimal swift CRUD would be useful to act as a smoke test and prevent regressions, for issues like #417 for example.

I have a minimal swift project locally but PRing it and getting it to run on jenkins/travis is a non-trivial amount of work.

**Comment by ricellis** [comment]
This library is now end-of-life and this issue won't be fixed.
This issue has been [tagged `EOL`](https://github.com/cloudant/CDTDatastore/issues?q=is%3Aissue+label%3AEOL) in case any forks want to import it.
