### ISSUE TITLE
Is there any way to get the progress of the replication?

### ISSUE THREAD

**Issue by navaneet** [cloudant/CDTDatastore#416]
We have been trying to show progress for replication however the api provided
```
func replicatorDidChangeProgress(_ replicator: CDTReplicator) {
        Log.debug("Synced \(replicator.changesProcessed) / \(replicator.changesTotal) changes read from the source's feed")
    }
```

the value of changesTotal keeps on updating as the replication progresses. Since we have a big database, initial replication takes a lot of time for which showing an indeterminate progress bar is not very user friendly. Is there any api we can use to get the exact number of documents to be downloaded during a filtered replication from the library itself ?

**Comment by smithsz** [comment]
Sorry for the belated response. It isn't currently possible to establish the progress of a replication.

Under the hood we submit a filtered changes feed to the server in order to collect document revisions that need fetching. We only get the full list once this request completes. Therefore knowing the work required to synchronise a database in advance isn't currently possible.

Thanks.
